### PR TITLE
Expose RouteSettings on show picker function

### PR DESCRIPTION
**Pull request by naipaka**
Expose RouteSettings in the show picker function.
This modification enables tracking transitions to the Picker component using tools such as FirebaseAnalytics.

### CODE REVIEW

**Comment by naipaka** [comment]
Hello @subhamayd2 ,

I noticed that some time has passed since I submitted this pull request, and I wanted to check in on the status. If there are any issues or concerns, could you please let me know? I'm eager to contribute to the project and am willing to provide additional information or make changes as needed.

Thank you for your time and consideration.

Best regards.

**Comment by subhamayd2** [comment]
Hey sorry for being late. I completely missed it. Would you mind adding an entry in the doc comment for the `settings` prop at the top of `daynight_timepicker.dart` file?

**Comment by subhamayd2** [comment]
@all-contributors please add @naipaka for code

**Comment by naipaka** [comment]
@subhamayd2 
No worries at all, and thank you for getting back to me. I've added the requested entry in the doc comment for the `settings` prop at the top of the `daynight_timepicker.dart` file. The content I added is the same as what I included in the `README.md` file. Please take a look and let me know if there's anything else I can assist with or modify.

**Comment by subhamayd2** [comment]
Looks good to me. Thanks for the contribution!

**Pull request merged**
